"""all models working well

Revision ID: 0e230b0e6ae4
Revises: 386889e3884e
Create Date: 2024-09-19 22:50:56.453374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e230b0e6ae4'
down_revision = '386889e3884e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
