"""Empty init

Revision ID: 386889e3884e
Revises: 
Create Date: 2024-09-19 20:44:43.553050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386889e3884e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
